IdeoZadanie/Models/Tree.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IdeoZadanie.Models
{
    public class Tree
    {
        public int Id { get; set; }
        
        [Required]
        public string Name { get; set; }

        [Display(Name ="Parent Name")]
        public int? ParentId { get; set; }
        public virtual Tree Parent { get; set; }
        public virtual ICollection<Tree> Childrens { get; set; }
    }
}

IdeoZadanie/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IdeoZadanie.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

IdeoZadanie/Controllers/TreesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IdeoZadanie.DAL;
using IdeoZadanie.Models;
using System.Data.Entity.Infrastructure;

namespace IdeoZadanie.Controllers
{
    public class TreesController : Controller
    {
        private TreeContext db = new TreeContext();

        // GET: Trees/2
        public ActionResult Index(int? id)
        {
            ViewBag.SelectedId = id;
            var trees = db.Trees.Include(t => t.Parent);
            return View(trees.ToList());
        }

        // GET: Trees/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tree tree = db.Trees.Find(id);
            if (tree == null)
            {
                return HttpNotFound();
            }
            return View(tree);
        }

        // GET: Trees/Create
        public ActionResult Create(int? id)
        {
            ViewBag.Parent = null;
            ViewBag.ParentName = null;
            if (id != null)
            {
                Tree parent = db.Trees.SingleOrDefault(t => t.Id == id);
                if (parent != null)
                {
                    ViewBag.Parent = id;
                    ViewBag.ParentName = parent.Name;
                }
            }
            //ViewBag.ParentId = new SelectList(db.Trees, "Id", "Name");
            return View();
        }

        // POST: Trees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
           public ActionResult Create([Bind(Include = "Id,Name")] Tree tree, int? id)
        {
            if (ModelState.IsValid)
            {
                db.Trees.Add(tree);
                db.SaveChanges();
                if (id != null)
                {
                    Tree parent = db.Trees.SingleOrDefault(t => t.Id == id);
                    if (parent != null)
                    {
                        tree.Parent = parent;
                    }
                    else
                    {
                        tree.Parent = tree;
                    }
                }
                else
                {
                    tree.Parent = tree;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ParentId = new SelectList(db.Trees, "Id", "Name", tree.ParentId);
            return View(tree);
        }

        // GET: Trees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tree tree = db.Trees.Find(id);
            if (tree == null)
            {
                return HttpNotFound();
            }
            ViewBag.ParentId = GetSelectListFor(tree);
            return View(tree);
        }

        // POST: Trees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,ParentId")] Tree tree)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tree).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ParentId = GetSelectListFor(tree);
            return View(tree);
        }

        // GET: Trees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tree tree = db.Trees.Find(id);
            if (tree == null)
            {
                return HttpNotFound();
            }
            return View(tree);
        }

        // POST: Trees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tree tree = db.Trees.Find(id);
            RemoveChildrensFromDatabase(tree);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        private void RemoveChildrensFromDatabase(Tree tree)
        {
            if (tree.Childrens.Where(t => t.Id != tree.Id).ToList().Count > 0)
            {
                foreach (Tree t in tree.Childrens.Where(t => t.Id != tree.Id).ToList())
                {
                    RemoveChildrensFromDatabase(t);
                }
            }
            db.Trees.Remove(tree);
        }

        // GET: Trees/Move/5
        public ActionResult Move(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tree tree = db.Trees.Find(id);
            if (tree == null)
            {
                return HttpNotFound();
            }
            ViewBag.ParentId = GetSelectListFor(tree);
            return View(tree);
        }

        // POST: Trees/Move/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Move([Bind(Include = "Id, Name, ParentId")]Tree tree)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tree).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ParentId = GetSelectListFor(tree);
            return View(tree);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private SelectList GetSelectListFor(Tree tree)
        {
            List<Tree> trees = GetListWithoutChildrens(db.Trees.ToList(), tree);
            if (!trees.Contains(tree)) trees.Add(tree);

            return new SelectList(trees, "Id", "Name", tree.ParentId); ;
        }

        private List<Tree> GetListWithoutChildrens(List<Tree> trees, Tree tree)
        {
            foreach (Tree t in tree.Childrens)
            {
                if (t.Childrens.Count > 0 && t.Id != tree.Id)
                {
                    trees = GetListWithoutChildrens(trees, t);
                }
                trees.Remove(t);
            }
            return trees;
        }
    }
}

IdeoZadanie/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Tree View Application</h1>
</div>
<div class="row">
    <div class="col-md-10">
        <h2>Welcome to Tree View Application</h2>
        <p>
            Tree View Application was created
            for Ideo recruitment.
        </p>
    </div>
</div>

IdeoZadanie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Tree View Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Tree View", "Index", "Trees", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Tree View", "Index", "Trees")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Tree View Application</p>
            <p>Made by Piotr Knapik</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

IdeoZadanie/Views/Trees/Create.cshtml
@model IdeoZadanie.Models.Tree

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Tree</h4>
        @if (ViewBag.ParentName != null)
        {
        <h6>This will be a child of @ViewBag.ParentName</h6>
        }
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ParentId)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IdeoZadanie/Views/Trees/Delete.cshtml
@model IdeoZadanie.Models.Tree

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tree</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ParentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Parent.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

IdeoZadanie/Views/Trees/Details.cshtml
@model IdeoZadanie.Models.Tree

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Tree</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ParentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Parent.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IdeoZadanie/Views/Trees/Edit.cshtml
@model IdeoZadanie.Models.Tree

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tree</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ParentId, "ParentId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ParentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ParentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IdeoZadanie/Views/Trees/Index.cshtml
@model IEnumerable<IdeoZadanie.Models.Tree>

@{
    ViewBag.Title = "Index";
}

@{
    string GetPath(IdeoZadanie.Models.Tree tree)
    {
        IdeoZadanie.Models.Tree t = tree;
        string path = tree.Name;
        while (t != t.Parent)
        {
            path = t.Parent.Name + " > " + path;
            t = t.Parent;
        }
        return path;
    }
}

@helper DisplayList(IdeoZadanie.Models.Tree tree)
{
    <li>
        <div class="btn-group" role="group" aria-label="...">
            <a href='@Url.Action("Delete", "Trees", new { id = tree.Id})'>
                <span class="glyphicon glyphicon-trash"></span>
            </a>
            <a href='@Url.Action("Edit", "Trees", new { id = tree.Id})'>
                <span class="glyphicon glyphicon-pencil"></span>
            </a>
            <a href='@Url.Action("Create", "Trees", new { id = tree.Id})'>
                <span class="glyphicon glyphicon-plus"></span>
            </a>
        </div>
        @if (tree.Childrens.Where(tr => tr.Id != tree.Id).ToList().Count > 0)
        {
            <span class="caretList">@Html.ActionLink(tree.Name, "Index", new { id = tree.Id })</span>
            <ul class="nested">
                @foreach (var t in tree.Childrens.Where(tr => tr.Id != tree.Id))
                {
                    @DisplayList(t);
                }
            </ul>
        }
        else
        {
            @Html.ActionLink(tree.Name, "Index", new { id = tree.Id })
        }
    </li>
}

<h2>Index</h2>


<div class="detailContainer">
    <div class="treeList">
        <ul id="list">
            @foreach (var item in Model.Where(tree => tree.ParentId == tree.Id))
            {
                @DisplayList(item)
            }
            <li>
                <a href='@Url.Action("Create", "Trees")'>
                    <span class="glyphicon glyphicon-plus"></span>Add new root
                </a>
            </li>
        </ul>
    </div>
    <div class="selectedDetail">
        @if (ViewBag.SelectedId != null)
        {
            IdeoZadanie.Models.Tree t = Model.Where(tree => tree.Id == ViewBag.SelectedId).SingleOrDefault();
            <div class="detailName">    
                <h2 class="noMargin">@Html.DisplayFor(tree => t.Name)</h2>
                <h6>@GetPath(t)</h6>
            </div>
            <div class="detailList">
                <ul id="list">
                    @foreach (IdeoZadanie.Models.Tree tree in t.Childrens.Where(tr => tr.Id != t.Id))
                    {
                        <li>
                            @Html.ActionLink(tree.Name, "Index", new { id = tree.Id })
                        </li>
                    }
                    <li>
                        <a href='@Url.Action("Create", "Trees", new { id = t.Id })'>
                            <span class="glyphicon glyphicon-plus"></span>Add new child
                        </a>
                    </li>
                </ul>
            </div>
        }
    </div>
</div>

IdeoZadanie/Views/Trees/Move.cshtml
@model IdeoZadanie.Models.Tree

@{
    ViewBag.Title = "Move";
}

<h2>Move</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Are you sure you want to move "@Html.DisplayFor(model => model.Name)" from "@Html.DisplayFor(model => model.Parent.Name)" with all his childrens?</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Name)
        <div class="form-group">
            @Html.LabelFor(model => model.ParentId, "ParentId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ParentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ParentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
